name: PlayTime
api: 4.0.0
author: TPE
version: 1.0.0
main: TPE\PlayTime\Main

commands:
  playtime:
    permission: playtime.command
    description: Informs the user how much time has passed since they first joined the server.

permissions:
  playtime.command:
    default: true
